// Regenerate src/index.css from the design prototype's inline <style>
// (../QueryHub.html) + CODE-owned additions (src/index.local.css).
//
// Runs as the npm "prebuild" step, so every `npm run build` picks up design
// CSS changes automatically — no more hand-copying the <style> block (which
// silently drifted). To update the design CSS: refresh ../QueryHub.html from
// the prototype's <style> block and rebuild. For styling that is ahead of it:
// edit index.local.css.
// Do NOT hand-edit src/index.css — it is overwritten here.
import { readFileSync, writeFileSync } from 'node:fs';

const html = readFileSync(new URL('../QueryHub.html', import.meta.url), 'utf8');
const m = html.match(/<style>([\s\S]*?)<\/style>/);
if (!m) {
  console.error('gen-css: no <style> block in QueryHub.html');
  process.exit(1);
}
const design = m[1].replace(/^\n+|\s+$/g, '');

let local = '';
try {
  local = readFileSync(new URL('./src/index.local.css', import.meta.url), 'utf8').trim();
} catch { /* no local additions — fine */ }

const header =
  '/* GENERATED by gen-css.mjs — do NOT edit.\n' +
  '   Design CSS = ../QueryHub.html <style>; local additions = src/index.local.css.\n' +
  '   Run `npm run build` (prebuild) to regenerate. */\n';
const out = header + design +
  (local ? '\n\n/* ---- local additions (CODE-owned; override the design above) ---- */\n' + local + '\n' : '\n');

writeFileSync(new URL('./src/index.css', import.meta.url), out);
console.log(`gen-css: wrote src/index.css (${out.length} bytes; design + ${local ? 'local' : 'no-local'})`);
