#!/usr/bin/env bash
# Regenerate the bundled webfonts (QueryHubWeb/fonts/ + QueryHubWeb/fonts.css).
#
# The web UI self-hosts Manrope and IBM Plex Mono rather than linking Google
# Fonts: the app is otherwise entirely self-contained, so a CDN link was the one
# thing that leaked a request (and the viewer's IP) to a third party, tripped the
# app's own CSP, and broke the UI on an air-gapped install.
#
# You only need this when changing weights/subsets or refreshing the files — the
# fonts are committed, so a normal build and a normal install need no network.
#
# Both families are SIL OFL 1.1; see QueryHubWeb/fonts/LICENSE-fonts.txt.
set -euo pipefail

cd "$(dirname "$0")/.."
FONT_DIR=QueryHubWeb/fonts
CSS_OUT=QueryHubWeb/fonts.css
# Subsets to keep. latin + latin-ext covers English plus accented names; add
# more (cyrillic, greek, vietnamese) only if you need them — each is another
# file per weight.
SUBSETS="latin latin-ext"
QUERY='family=Manrope:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500;600&display=swap'
# A modern UA is required or Google serves ttf instead of woff2.
UA='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36'

mkdir -p "$FONT_DIR"
TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT
curl -sSf -A "$UA" "https://fonts.googleapis.com/css2?${QUERY}" -o "$TMP/gf.css"

SUBSETS="$SUBSETS" FONT_DIR="$FONT_DIR" CSS_OUT="$CSS_OUT" TMP="$TMP" UA="$UA" \
python3 - <<'PY'
import os, re, pathlib, subprocess

keep = set(os.environ["SUBSETS"].split())
font_dir = pathlib.Path(os.environ["FONT_DIR"])
css = pathlib.Path(os.environ["TMP"], "gf.css").read_text()
parts = re.split(r"/\*\s*([a-z-]+)\s*\*/", css)

header = """/* Self-hosted webfonts — do not add a CDN link for these.
 *
 * Generated by scripts/fetch_webfonts.sh. Manrope and IBM Plex Mono are both
 * SIL OFL 1.1; see fonts/LICENSE-fonts.txt. Only latin + latin-ext are shipped,
 * which covers English plus accented names.
 */"""
rules, downloaded = [header], 0
for i in range(1, len(parts) - 1, 2):
    subset, body = parts[i], parts[i + 1]
    if subset not in keep:
        continue
    fam = re.search(r"font-family:\s*'([^']+)'", body)
    wgt = re.search(r"font-weight:\s*(\d+)", body)
    url = re.search(r"url\((https://fonts\.gstatic\.com/[^)]+\.woff2)\)", body)
    rng = re.search(r"unicode-range:\s*([^;]+);", body)
    if not (fam and wgt and url):
        continue
    slug = f"{fam.group(1).replace(' ', '')}-{wgt.group(1)}-{subset}"
    subprocess.run(["curl", "-sSf", "-A", os.environ["UA"], url.group(1),
                    "-o", str(font_dir / f"{slug}.woff2")], check=True)
    downloaded += 1
    rules.append(f"""@font-face {{
  font-family: '{fam.group(1)}';
  font-style: normal;
  font-weight: {wgt.group(1)};
  font-display: swap;
  src: url('./fonts/{slug}.woff2') format('woff2');
  unicode-range: {rng.group(1).strip() if rng else 'U+0000-00FF'};
}}""")
pathlib.Path(os.environ["CSS_OUT"]).write_text("\n".join(rules) + "\n")
print(f"fetched {downloaded} font files -> {font_dir}")
print(f"wrote {os.environ['CSS_OUT']}")
PY

echo "Now rebuild the frontend: cd QueryHubWeb/app && npm run build"
