#!/usr/bin/env python3
"""Design-independent audit of the QueryHub Web frontend wiring.

Run after refreshing the prototype components and re-applying the integration
wiring, to prove nothing regressed:

  * no CONSUMED mock data/helpers leaked into the wired components,
  * no racy tab-focus (setActiveId('t' + (TAB_SEQ - 1))) — focus by real id,
  * no dangling calls to removed mock functions,
  * every `st.<X>` the admin views use is provided by useAdminState,
  * every `qhApi.<X>` the components call exists in qh-api.jsx.

Exit 0 = clean. Non-zero = review the reported items. This does NOT judge
design or layout — only the integration seam.
"""
from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent / "QueryHubWeb"
# The wired application components (NOT qh-data.jsx, which still *defines*
# client helpers + dead mock; only its live helpers are consumed).
WIRED = ["qh-app.jsx", "qh-panels.jsx", "qh-editor.jsx", "qh-login.jsx",
         "qh-admin.jsx", "qh-admin-access.jsx", "qh-admin-insights.jsx"]
ADMIN_VIEWS = ["qh-admin.jsx", "qh-admin-access.jsx", "qh-admin-insights.jsx"]

# Mock symbols that must NOT be consumed by the wired components (they are
# replaced by real API calls / the /schema cache / result.piiCols).
FORBIDDEN = [
    "qhColumnsFor", "qhIndexesFor", "qhViewsFor", "qhApproxRows",
    "QH_PII_CATALOG", "qhMaskValue", "qhMockResult", "qhExplainPlan",
    "QH_CONNECTIONS", "QH_HISTORY", "Robin Fox", "qhServerRoles",
]


def read(name: str) -> str:
    p = ROOT / name
    return p.read_text() if p.exists() else ""


def main() -> int:
    problems: list[str] = []

    # 1. no consumed mock in the wired components
    for f in WIRED:
        s = read(f)
        for sym in FORBIDDEN:
            if sym in s:
                problems.append(f"{f}: consumes mock `{sym}`")
        if re.search(r"useAdminStateHook\(QH_\w+SEED", s) or "QH_SAVED[" in s:
            problems.append(f"{f}: references a mock seed")

    # 2. no racy tab focus
    for f in WIRED:
        if "setActiveId('t' + (TAB_SEQ" in read(f):
            problems.append(f"{f}: racy setActiveId('t'+(TAB_SEQ-1)) — focus by f.id")

    # 3. no dangling calls to removed mock run-flow fns
    app = read("qh-app.jsx")
    for pat in (r"\bexecute\(", r"\brunDirect\("):
        if re.search(pat, app):
            problems.append(f"qh-app.jsx: dangling `{pat}`")

    # 4. every st.<X> the admin views use is provided by useAdminState
    admin_data = read("qh-admin-data.jsx")
    m = re.search(r"return \{\s*(.*?)\s*\};", admin_data, re.S)
    provided = set(re.findall(r"[a-zA-Z]+", m.group(1))) if m else set()
    used = set()
    for f in ADMIN_VIEWS:
        # The lookbehind matters: without it, `cost.dbaHoursSaved` and
        # `list.map` match as `st.<field>` and the check reports seven fields
        # that were never state fields at all.
        used |= set(re.findall(r"(?<![A-Za-z0-9_$])st\.([a-zA-Z]+)", read(f)))
    # `st` is also passed around and iterated, so array/function members show
    # up. They are not state fields and reporting them buries the real misses.
    used -= {"length", "map", "filter", "forEach", "find", "slice", "concat"}
    for u in sorted(used - provided):
        problems.append(f"admin views use st.{u} but useAdminState does not return it")

    # 4b. app/src/index.css is GENERATED by app/gen-css.mjs from QueryHub.html's
    #     <style> plus src/index.local.css. This check used to compare the two
    #     byte-for-byte, from the days when index.css was a hand-copied lift — so
    #     it reported "out of sync" on every run once the generator started adding
    #     a header and appending the local additions. A check that always fails is
    #     a check nobody reads, so reproduce what the generator writes and compare
    #     against that instead.
    html = read("QueryHub.html")
    m = re.search(r"<style>(.*?)</style>", html, re.S)
    idx = ROOT / "app" / "src" / "index.css"
    if m and idx.exists():
        design = re.sub(r"^\n+|\s+$", "", m.group(1))
        local_path = ROOT / "app" / "src" / "index.local.css"
        local = local_path.read_text().strip() if local_path.exists() else ""
        header = ("/* GENERATED by gen-css.mjs — do NOT edit.\n"
                  "   Design CSS = ../QueryHub.html <style>; local additions = "
                  "src/index.local.css.\n"
                  "   Run `npm run build` (prebuild) to regenerate. */\n")
        expected = header + design + (
            "\n\n/* ---- local additions (CODE-owned; override the design above) "
            "---- */\n" + local + "\n" if local else "\n")
        if idx.read_text() != expected:
            problems.append(
                "app/src/index.css does not match gen-css.mjs output — run "
                "`cd QueryHubWeb/app && npm run build` (the prebuild step "
                "regenerates it) so design/local CSS changes reach the bundle")

    # 5. every qhApi.<X> called exists in qh-api.jsx
    api = read("qh-api.jsx")
    defined = set(re.findall(r"\b([a-zA-Z]+)\s*:", api)) | set(re.findall(r"function (qh\w+)", api))
    called = set()
    for f in WIRED + ["qh-admin-data.jsx"]:
        called |= set(re.findall(r"qhApi\.([a-zA-Z]+)", read(f)))
    for c in sorted(called - defined):
        problems.append(f"qhApi.{c} is called but not defined in qh-api.jsx")

    if problems:
        print(f"web-wiring: {len(problems)} issue(s):")
        for p in problems:
            print(f"  - {p}")
        return 1
    print("web-wiring: clean — no consumed mock, no racy focus, no dangling "
          "calls, st.* + qhApi.* fully provided.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
